2024-09-25 07:50:02,998 - INFO - Attempting to download from URL: https://www.instagram.com/reel/DAAbYbENY8Q/
2024-09-25 07:50:02,998 - INFO - Extracted shortcode: DAAbYbENY8Q
2024-09-25 07:50:05,341 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-09-25 07:50:05,607 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-09-25 07:50:06,575 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-09-25 07:50:08,805 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-09-25 07:50:08,808 - ERROR - An error occurred: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D
Traceback (most recent call last):
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/u926199223/domains/karharimedia.net/public_html/public/../script.py", line 25, in main
    post = Post.from_shortcode(loader.context, shortcode)
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/structures.py", line 207, in from_shortcode
    post._node = post._full_metadata
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/structures.py", line 335, in _full_metadata
    self._obtain_metadata()
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/structures.py", line 322, in _obtain_metadata
    pic_json = self._context.graphql_query(
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 511, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 468, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D
2024-09-25 07:58:19,338 - INFO - Attempting to download from URL: https://www.instagram.com/reel/DAAbYbENY8Q/
2024-09-25 07:58:19,339 - INFO - Extracted shortcode: DAAbYbENY8Q
2024-09-25 07:58:19,926 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-09-25 07:58:20,209 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-09-25 07:58:24,480 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-09-25 07:58:29,035 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-09-25 07:58:29,037 - WARNING - Connection error, retrying in 5 seconds...
2024-09-25 07:58:36,633 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-09-25 07:58:36,896 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-09-25 07:58:37,874 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-09-25 07:58:39,311 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-09-25 07:58:39,314 - WARNING - Connection error, retrying in 5 seconds...
2024-09-25 07:58:44,507 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-09-25 07:58:44,775 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-09-25 07:58:46,309 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-09-25 07:58:50,402 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-09-25 07:58:50,404 - ERROR - An error occurred: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D
Traceback (most recent call last):
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/u926199223/domains/karharimedia.net/public_html/public/../script.py", line 34, in main
    post = Post.from_shortcode(loader.context, shortcode)
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/structures.py", line 207, in from_shortcode
    post._node = post._full_metadata
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/structures.py", line 335, in _full_metadata
    self._obtain_metadata()
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/structures.py", line 322, in _obtain_metadata
    pic_json = self._context.graphql_query(
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 511, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/home/u926199223/python3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 468, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D
2024-10-01 17:44:42,458 - INFO - Attempting to download from URL: https://www.instagram.com/reel/DAQF4U0xN9z/?utm_source=ig_web_copy_link
2024-10-01 17:44:42,458 - INFO - Extracted shortcode: DAQF4U0xN9z
2024-10-01 17:44:42,621 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-01 17:44:43,023 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:44:45,220 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:44:45,774 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:44:45,777 - WARNING - Connection error, retrying in 5 seconds...
2024-10-01 17:44:52,376 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-01 17:44:52,666 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:44:53,256 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:44:53,733 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:44:53,736 - WARNING - Connection error, retrying in 5 seconds...
2024-10-01 17:44:59,908 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-01 17:45:00,229 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:45:02,546 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:45:03,358 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:45:03,360 - ERROR - An error occurred: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/twizzledream/htdocs/www.twizzledream.com/instagram.py", line 34, in main
    post = Post.from_shortcode(loader.context, shortcode)
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 207, in from_shortcode
    post._node = post._full_metadata
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 335, in _full_metadata
    self._obtain_metadata()
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 322, in _obtain_metadata
    pic_json = self._context.graphql_query(
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 511, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 468, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D
2024-10-01 17:46:25,616 - INFO - Attempting to download from URL: https://www.instagram.com/reels/DAQF4U0xN9z/
2024-10-01 17:46:25,616 - INFO - Extracted shortcode: DAQF4U0xN9z
2024-10-01 17:46:25,925 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-01 17:46:26,255 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:46:28,972 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:46:29,803 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:46:29,806 - WARNING - Connection error, retrying in 5 seconds...
2024-10-01 17:46:34,865 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-01 17:46:35,161 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:46:36,845 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:46:37,786 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:46:37,788 - WARNING - Connection error, retrying in 5 seconds...
2024-10-01 17:46:43,113 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-01 17:46:43,413 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:46:50,336 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:46:55,592 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D HTTP/1.1" 401 119
2024-10-01 17:46:55,594 - ERROR - An error occurred: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/twizzledream/htdocs/www.twizzledream.com/instagram.py", line 34, in main
    post = Post.from_shortcode(loader.context, shortcode)
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 207, in from_shortcode
    post._node = post._full_metadata
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 335, in _full_metadata
    self._obtain_metadata()
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 322, in _obtain_metadata
    pic_json = self._context.graphql_query(
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 511, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 468, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAQF4U0xN9z%22%7D
2024-10-01 17:53:51,235 - INFO - Attempting to download from URL: https://www.instagram.com/reel/DAAbYbENY8Q/
2024-10-01 17:53:51,235 - INFO - Extracted shortcode: DAAbYbENY8Q
2024-10-01 17:53:52,033 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-01 17:53:52,383 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:53:53,656 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:53:56,405 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:53:56,408 - WARNING - Connection error, retrying in 5 seconds...
2024-10-01 17:54:01,788 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-01 17:54:02,090 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:05,564 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:08,429 - INFO - Attempting to download from URL: https://www.instagram.com/reel/DAAbYbENY8Q/
2024-10-01 17:54:08,430 - INFO - Extracted shortcode: DAAbYbENY8Q
2024-10-01 17:54:08,524 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:08,527 - WARNING - Connection error, retrying in 5 seconds...
2024-10-01 17:54:11,184 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-01 17:54:11,485 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:13,245 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:15,421 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-01 17:54:15,709 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:16,134 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:16,282 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:16,285 - WARNING - Connection error, retrying in 5 seconds...
2024-10-01 17:54:17,146 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:17,148 - ERROR - An error occurred: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/twizzledream/htdocs/www.twizzledream.com/instagram.py", line 34, in main
    post = Post.from_shortcode(loader.context, shortcode)
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 207, in from_shortcode
    post._node = post._full_metadata
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 335, in _full_metadata
    self._obtain_metadata()
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 322, in _obtain_metadata
    pic_json = self._context.graphql_query(
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 511, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 468, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D
2024-10-01 17:54:21,391 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-01 17:54:21,766 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:23,832 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:31,551 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:31,554 - WARNING - Connection error, retrying in 5 seconds...
2024-10-01 17:54:36,636 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-01 17:54:36,948 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:40,354 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:40,986 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/1.1" 401 119
2024-10-01 17:54:40,989 - ERROR - An error occurred: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/twizzledream/htdocs/www.twizzledream.com/instagram.py", line 34, in main
    post = Post.from_shortcode(loader.context, shortcode)
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 207, in from_shortcode
    post._node = post._full_metadata
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 335, in _full_metadata
    self._obtain_metadata()
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 322, in _obtain_metadata
    pic_json = self._context.graphql_query(
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 511, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 468, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D
2024-10-02 06:01:12,898 - INFO - Attempting to download from URL: https://www.instagram.com/reel/DAAbYbENY8Q/?hl=en
2024-10-02 06:01:12,899 - INFO - Extracted shortcode: DAAbYbENY8Q
2024-10-02 06:01:15,136 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-02 06:01:15,529 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-10-02 06:01:19,613 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-10-02 06:01:21,548 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-10-02 06:01:21,550 - WARNING - Connection error, retrying in 5 seconds...
2024-10-02 06:01:26,657 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-02 06:01:26,908 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-10-02 06:01:27,553 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-10-02 06:01:33,362 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-10-02 06:01:33,363 - WARNING - Connection error, retrying in 5 seconds...
2024-10-02 06:01:42,283 - DEBUG - Starting new HTTPS connection (1): www.instagram.com:443
2024-10-02 06:01:42,527 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-10-02 06:01:46,578 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-10-02 06:01:49,005 - DEBUG - https://www.instagram.com:443 "GET /graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D HTTP/11" 401 119
2024-10-02 06:01:49,007 - ERROR - An error occurred: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 456, in get_json
    raise ConnectionException(self._response_error(resp))
instaloader.exceptions.ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/twizzledream/htdocs/www.twizzledream.com/public/../instagram.py", line 34, in main
    post = Post.from_shortcode(loader.context, shortcode)
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 207, in from_shortcode
    post._node = post._full_metadata
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 335, in _full_metadata
    self._obtain_metadata()
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 322, in _obtain_metadata
    pic_json = self._context.graphql_query(
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 511, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 480, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 468, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DAAbYbENY8Q%22%7D
